export type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

export type IconVariant =
  | 'default'
  | 'muted'
  | 'brand'
  | 'success'
  | 'warning'
  | 'danger'
  | 'inverse';

export type IconName =
  // Arrows
  | 'arrow-up'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  // Chevrons
  | 'chevron-up'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  // UI Controls
  | 'menu'
  | 'close'
  | 'more-horizontal'
  | 'more-vertical'
  // Basic
  | 'plus'
  | 'minus'
  | 'check'
  | 'slash'
  // Edit & File Actions
  | 'edit'
  | 'trash'
  | 'copy'
  | 'download'
  | 'upload'
  | 'refresh'
  | 'search'
  | 'filter'
  | 'sort'
  | 'share'
  | 'link'
  | 'external-link'
  | 'send'
  | 'print'
  | 'save'
  // Status & Feedback
  | 'check-circle'
  | 'x-circle'
  | 'info'
  | 'alert-triangle'
  | 'alert-circle'
  | 'clock'
  | 'calendar'
  | 'loader'
  // User & Account
  | 'user'
  | 'users'
  | 'log-in'
  | 'log-out'
  | 'settings'
  // Navigation & Location
  | 'home'
  | 'map-pin'
  | 'globe'
  | 'bookmark'
  | 'flag'
  | 'tag'
  // Communication
  | 'mail'
  | 'phone'
  | 'message'
  | 'bell'
  | 'at'
  | 'rss'
  // Files & Data
  | 'file'
  | 'file-text'
  | 'folder'
  | 'image'
  | 'code'
  | 'terminal'
  | 'package'
  | 'database'
  | 'server'
  | 'cloud'
  // Security
  | 'eye'
  | 'eye-off'
  | 'lock'
  | 'unlock'
  | 'key'
  | 'shield'
  // Favorites
  | 'star'
  | 'heart'
  // Media
  | 'play'
  | 'pause'
  | 'stop'
  | 'volume'
  | 'volume-off'
  | 'mic'
  | 'camera'
  | 'video'
  // Layout & View
  | 'grid'
  | 'list'
  | 'maximize'
  | 'minimize'
  | 'sidebar'
  | 'layers'
  | 'zoom-in'
  | 'zoom-out'
  // Theme & Misc
  | 'sun'
  | 'moon';
